name: first github actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
 IMAGE_NAME: krishnapuppala97/pk
 IMAGE_TAG: ${{github.run_id}}
jobs:
  java-maven:
    runs-on: ubuntu-latest
    permissions:
     id-token: write
     contents: read
    steps:
      - uses: actions/checkout@v2
      - name: install java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: build artifact
        run: mvn clean package install
     # - name: Set up QEMU
     #   uses: docker/setup-qemu-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     # - name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2
      #- name: Build and push
       # uses: docker/build-push-action@v3
       # with:
        #  context: .
         # file: ./Dockerfile
         # push: true
         # tags: ${{ secrets.DOCKERHUB_USERNAME }}/pk:latest
     # - name: docker build & push
      #  run: |
       #       docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/pk:latest .
        #      docker push ${{ secrets.DOCKERHUB_USERNAME }}/pk:latest
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::989189644101:role/github_actions
          aws-region: us-east-1
