name: first github actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
 IMAGE_NAME: krishnapuppala97/pk
 IMAGE_TAG: ${{github.run_id}}
jobs:
  java-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
